export const mmToInches=(mm:number)=>mm/25.4;
export const speedUnit=(kmh:number,imperial:boolean)=>imperial?kmh/1.609344:kmh;
export function mounted(bsd:number,width:number,measured?:number){if(bsd<=0||width<=0)throw Error('BSD and tire width must be positive.');const diameter=measured||bsd+2*width;return {diameter,circumference:Math.PI*diameter};}
export function gear(front:number,rear:number,diameter:number,cadence:number){if([front,rear,diameter,cadence].some(n=>n<=0||!Number.isFinite(n)))throw Error('Enter positive values for all gear inputs.');const ratio=front/rear,development=Math.PI*diameter/1000*ratio;return {ratio,development,speed:development*cadence*60/1000,inches:diameter/25.4*ratio};}
export function equivalents(target:number,front:number,cogs:number[],diameter:number){return cogs.map((cog,index)=>{const g=gear(front,cog,diameter,90);return {...g,cog,position:index+1,difference:(g.development/target-1)*100}}).sort((a,b)=>Math.abs(a.difference)-Math.abs(b.difference));}
export function fit(height:number,inseam:number,style:string,torso?:number,arm?:number){if(height<120||height>220||inseam<=0||inseam>=height)throw Error('Height must be 120–220 cm and inseam must be shorter than height.');const sport=style==='Sport'||style==='Aero / TT';const stack=height*3.15+(sport?-15:15);const reach=height*2.22+(torso&&arm?(torso+arm-110)*1.5:0);return {stack:[stack-18,stack+18],reach:[reach-12,reach+12],saddle:[inseam*8.7,inseam*8.9],crank:height<170?[160,170]:[165,175],confidence:torso&&arm?'Medium':'Low'};}
export function rolling(mass:number,speed:number,crr:number){if(mass<=0||speed<=0||crr<=0)throw Error('Mass, speed and Crr must be positive.');return mass*9.80665*crr*speed/3.6;}
export type Component={model:string;family:string;speeds:number;maxCog?:number;capacity?:number};
export function compatibility(shifter:Component,rd:Component,chain:Component,cassette:Component&{sprockets:number[]},rings:number[]){const spread=Math.max(...rings)-Math.min(...rings);const demand=spread+Math.max(...cassette.sprockets)-Math.min(...cassette.sprockets);return [{label:'Shifter ↔ rear derailleur',ok:shifter.family===rd.family,reason:`${shifter.family} / ${rd.family}; matching speed counts alone is insufficient.`},{label:'Cassette speed',ok:shifter.speeds===cassette.speeds,reason:`${shifter.speeds}-speed shifter and ${cassette.speeds}-speed cassette.`},{label:'Chain system',ok:chain.family===cassette.family,reason:`${chain.family} / ${cassette.family}; conservative sample-system match.`},{label:'Largest sprocket',ok:!!rd.maxCog&&Math.max(...cassette.sprockets)<=rd.maxCog,reason:`${Math.max(...cassette.sprockets)}T cassette maximum / ${rd.maxCog??'unknown'}T RD limit.`},{label:'Total capacity',ok:!!rd.capacity&&demand<=rd.capacity,reason:`(${Math.max(...rings)} − ${Math.min(...rings)}) + (${Math.max(...cassette.sprockets)} − ${Math.min(...cassette.sprockets)}) = ${demand}T / ${rd.capacity??'unknown'}T.`}];}
